// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "hrHCjWh0NExCA2Z5yPQPiROfO3YW7BTFdaR2cmzcpuPze6xw3x0hRvpNCYAekjJlDJ1c5z";
}
}
}

